### ISSUE TITLE
Add Sentry monitoring for new frontend code

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#112]
Here is some AI generated help:

If your React.js app uses TypeScript, the process of setting up Sentry is very similar, with some type adjustments. Below is a TypeScript-specific guide:

---

### **1. Install the Sentry SDK**
Same as in JavaScript, you install the Sentry React SDK:
```bash
npm install @sentry/react @sentry/tracing
```

---

### **2. Initialize Sentry in Your App**
In your `src/index.tsx` (or equivalent entry point), add the following:

```typescript
import React from 'react';
import ReactDOM from 'react-dom/client';
import * as Sentry from '@sentry/react';
import { BrowserTracing } from '@sentry/tracing';

import App from './App';

Sentry.init({
  dsn: 'https://YOUR_SENTRY_DSN@sentry.io/YOUR_PROJECT_ID', // Replace with your DSN
  integrations: [new BrowserTracing()],
  
  // Performance monitoring
  tracesSampleRate: 1.0, // Adjust this value for production
});

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
root.render(<App />);
```

Note:
- The `document.getElementById` call needs a type assertion (`as HTMLElement`) because TypeScript enforces strict DOM typing.

---

### **3. Add Error Boundaries with Type Safety**
Use Sentry's `ErrorBoundary` with proper TypeScript types:

```typescript
import * as Sentry from '@sentry/react';

const App: React.FC = () => (
  <Sentry.ErrorBoundary fallback={<p>Something went wrong.</p>}>
    <YourComponent />
  </Sentry.ErrorBoundary>
);

export default App;
```

---

### **4. Capture Errors Manually**
You can log exceptions or custom events in a type-safe way:

```typescript
try {
  throw new Error("Oops, something went wrong!");
} catch (error) {
  Sentry.captureException(error); // Works seamlessly with TypeScript's Error type
}

// Custom message
Sentry.captureMessage("Custom log message");
```

---

### **5. Add Types for Environment Configuration**
If you use environment variables (e.g., `process.env`), TypeScript requires type declarations. Add them in a `global.d.ts` file:

```typescript
// src/types/global.d.ts
declare namespace NodeJS {
  interface ProcessEnv {
    REACT_APP_SENTRY_DSN: string;
    NODE_ENV: 'development' | 'production' | 'test';
  }
}
```

Then use them in your `Sentry.init` call:
```typescript
Sentry.init({
  dsn: process.env.REACT_APP_SENTRY_DSN,
  environment: process.env.NODE_ENV,
});
```

---

### **6. Handle Sensitive Data**
You can use TypeScript's type system to ensure data filtering functions are robust:

```typescript
Sentry.init({
  dsn: 'https://YOUR_SENTRY_DSN@sentry.io/YOUR_PROJECT_ID',
  beforeSend(event: Sentry.Event): Sentry.Event | null {
    // Example: Remove sensitive user information
    if (event.user) {
      delete event.user.email;
    }
    return event;
  },
});
```

---

### **7. Source Maps for TypeScript**
To debug TypeScript stack traces in Sentry:
1. Configure your build tool to generate source maps (e.g., `tsconfig.json`):
   ```json
   {
     "compilerOptions": {
       "sourceMap": true
     }
   }
   ```
2. Upload source maps during deployment using Sentry's CLI:
   ```bash
   npx @sentry/cli releases files <RELEASE_VERSION> upload-sourcemaps ./build --url-prefix '~/static/js' --validate
   ```

---

### **8. Test the Integration**
You can test Sentry in TypeScript the same way as JavaScript:
```typescript
Sentry.captureException(new Error("Test Sentry error"));
```

---

### **Best Practices for TypeScript**
- **Strict Typing**: Use Sentry's TypeScript definitions to prevent type errors.
- **Custom Types**: If you extend Sentry events, define your custom event types in TypeScript.
- **Modular Setup**: Create a `sentry.ts` file to encapsulate your Sentry initialization logic and import it into `index.tsx` for better organization.

By following these steps, you’ll have a type-safe integration of Sentry in your React app!

**Comment by tsu-ki** [comment]
/assign
I would like to work on this issue :)

**Comment by arkid15r** [comment]
@tsu-ki any updates?

**Comment by tsu-ki** [comment]
@tsu-ki I've started working on the setup, as I wasn't aware of what Sentry did, I'm learning as I work with it. Please do let me know if I need to be swift with it

**Comment by arkid15r** [comment]
Well, you self-assigned the issue 2 weeks ago. It's enough time to either fix it or release for somebody else who would also like to contribute.
