### ISSUE TITLE
Migrate frontend to Node 22.x LTS

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#126]
Some AI generated hints:

To migrate the **Nest frontend** (from [[OWASP/Nest](https://github.com/OWASP/Nest/tree/main/frontend)](https://github.com/OWASP/Nest/tree/main/frontend)) from **Node 18** to **Node 22**, the scope of work would involve several key steps. Here's a breakdown of the tasks that would need to be completed:

### 1. **Update Node.js Version**
   - **Task**: Upgrade Node.js from version 18 to 22.
   - **Steps**:
     - Ensure that Node 22 is installed in the environment. This could be done using version managers like `nvm` or directly installing Node 22 via the Node.js website or package manager.
     - Update any `Dockerfile` (if applicable) or CI/CD configurations (e.g., GitHub Actions, Jenkins) to use Node 22.

### 2. **Update Dependencies**
   - **Task**: Ensure all frontend dependencies are compatible with Node 22.
   - **Steps**:
     - **Update package.json**:
       - Run `npm outdated` or `yarn outdated` to identify dependencies that need updating.
       - Update the version numbers for any outdated dependencies.
       - Check for breaking changes in dependencies. For example, certain libraries might be using deprecated Node APIs that were removed in Node 22.
     - **Check Compatibility**:
       - Investigate any specific dependencies that may not support Node 22 yet (e.g., older versions of Webpack, Babel, etc.). This can be done by reviewing the documentation for major dependencies or running `npm audit` for security and compatibility issues.
       - Ensure that any tools used for bundling (e.g., Webpack, Vite) or transpiling (e.g., Babel) are compatible with Node 22 and are updated if necessary.

### 3. **Address Breaking Changes**
   - **Task**: Resolve breaking changes introduced in Node 22.
   - **Steps**:
     - **Review Node.js 22 changelog**: Node 22 introduces new features and deprecates or removes older APIs. Review the [[Node.js v22 release notes](https://nodejs.org/en/blog/release/v22.x/)](https://nodejs.org/en/blog/release/v22.x/) to identify any breaking changes that could affect the frontend code.
     - **Check for deprecated APIs**: Look for deprecated or removed Node features like `timers.promises` (e.g., `setImmediate`) or changes to event handling mechanisms that could impact the frontend build pipeline or runtime.

### 4. **Testing and Debugging**
   - **Task**: Ensure that the application functions correctly after the migration.
   - **Steps**:
     - **Unit and Integration Tests**: Run all existing tests to confirm the frontend application works as expected with Node 22. This can include using testing frameworks like Jest or Mocha.
     - **Manual Testing**: Perform manual testing of the application, especially focusing on areas that interact with the Node.js runtime (e.g., file system handling, network requests).
     - **Check for performance regressions**: Test for any performance issues that might arise from the upgrade, particularly if the upgrade introduces more efficient internal Node features.

### 5. **Update Build and Deployment Configuration**
   - **Task**: Update build and deployment tools to work with Node 22.
   - **Steps**:
     - **Update CI/CD pipeline**: Make sure the build pipeline (e.g., GitHub Actions, Jenkins) is set to use Node 22. Update `.github/workflows` or `.gitlab-ci.yml` files accordingly.
     - **Dockerization**: If you're using Docker, update the `Dockerfile` to reference Node 22. Ensure that all necessary dependencies in the container image work with Node 22 as well.
     - **Testing environments**: Ensure your development, staging, and production environments are all updated to support Node 22.

### 6. **Documentation Updates**
   - **Task**: Update project documentation to reflect the migration.
   - **Steps**:
     - **Version Information**: Update `README.md` or similar documentation to reflect that the project now uses Node 22.
     - **Compatibility Guidelines**: If there are specific instructions for Node 22 compatibility, ensure they are clearly documented for future contributors.

### 7. **Monitor Post-Migration**
   - **Task**: Continuously monitor the application after the migration.
   - **Steps**:
     - **Log monitoring**: Keep an eye on logs and error reporting systems for issues that might not have been caught during testing.
     - **User feedback**: Be proactive in collecting feedback from users about any new issues post-migration.

### Conclusion
The scope of work mainly involves updating Node.js, dependencies, addressing breaking changes introduced by Node 22, running tests, and ensuring the deployment configurations are properly aligned with the new version. Regular checks on compatibility and performance will ensure a smooth migration process.

**Comment by yashpandey06** [comment]
I ll take up this ...let me know if any concerns !
