### ISSUE TITLE
Add project custom tags

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#144]
**Is your feature request related to a problem? Please describe.**
We want to be able to tag some projects with custom tags to improve search relevance.

**Describe the solution you'd like**
Add a new field to project model
```python
custom_tags = models.JSONField(verbose_name="Custom tags", default=list)
```
and index its contents. The field needs to be searchable in the index but there is _no_ need to add it to the project's card (frontend)

**Comment by harsh3dev** [comment]
I have figured it out the code changes but this part `The field needs to be searchable in the index` is a bit confusing.
Do you have any documentation for this?
I can add `custom_tags` to the `fields` and `searchableAttributes` but how do I verify that the changes work?

**Comment by arkid15r** [comment]
Hi @nitinawari 
any progress on this?

**Comment by nitinawari** [comment]
@arkid15r 
I was working on another issue earlier. I’ll start working on this now and will provide updates as soon as possible.

**Comment by arkid15r** [comment]
> @arkid15r I was working on another issue earlier. I’ll start working on this now and will provide updates as soon as possible.

Please avoid taking multiple issues at the same time -- other contributors could work on them while you're busy with other work.

**Comment by ansh7432** [comment]
heyy, can i work on this issue @arkid15r

**Comment by arkid15r** [comment]
> heyy, can i work on this issue @arkid15r

Hi @ansh7432 thanks for your willingness to contribute. I need this feature implemented sooner rather than later so I'm going to work on it today. However, I really want you to get involved in Nest development. Let me know (here on in Slack) what's your ideal good first issue would be (depending on your technical skills and backend/frontend knowledge). I hope I'll be able to find something for you.

**Comment by ansh7432** [comment]
Yeah Sure @arkid15r
