### ISSUE TITLE
Add project related repository descriptions to project index

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#146]
**Is your feature request related to a problem? Please describe.**
Project index should include related repositories description that can be used for better ranking.

**Describe the solution you'd like**
Update project index structure to include `idx_repository_descriptions` and use it for ranking as 2nd after the [idx_name](https://github.com/OWASP/Nest/blob/79f335df4d4da251b23df618f9bbff7a01872397/backend/apps/owasp/index/project.py#L56).

**Comment by yashpandey06** [comment]
Seems like a good problem

**Comment by arkid15r** [comment]
It was not that big. See the linked commit if you're interested in the implementation.
