### ISSUE TITLE
Index issues no older than 90 days

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#147]
**Is your feature request related to a problem? Please describe.**
There are about 6K issues in the index right now. Most of them are quite old.

**Describe the solution you'd like**
The idea is to modify [Issue index](https://github.com/OWASP/Nest/blob/3f577bcb8b539024b839b44668ceb39afeaa13da/backend/apps/github/index/issue.py#L75) to contain recent issues only (90d is a reasonable value). This should narrow the queryset down to about 600 issues.

The FR doesn't require any changes in GitHub issues sync process.

**Comment by yashpandey06** [comment]
Hey should I try resolving this issue ?

**Comment by arkid15r** [comment]
No assignee set so it's available -- go for it

**Comment by arkid15r** [comment]
@yashpandey06 any help with the PR needed?

**Comment by yashpandey06** [comment]
> @yashpandey06 any help with the PR needed?

@arkid15r  currently working on it ...got sick recently !!...will ask for help if needed .
