### ISSUE TITLE
Feat: Sorting feature for Project section

### ISSUE THREAD

**Issue by Rajgupta36** [OWASP/Nest#166]
### Problem Description
I find it difficult to locate specific projects in the Project section when the list is long and disorganized. Without a sorting option, it's time-consuming to browse through projects based on attributes like forks, contributions, or names.

---

### Solution
I would like to implement a sorting feature in the Project section. The list of projects should be sortable based on the following attributes:

- Forks count
- Contribution count
- Stars count
- Name

The sorting should support both ascending and descending order for each attribute, allowing users to easily organize and locate projects based on these criteria.

---

### Context
This feature would significantly improve the user experience by allowing users to sort projects quickly based on their needs.

**Comment by arkid15r** [comment]
This is duplicate of https://github.com/OWASP/Nest/issues/73
I doubt any work has been done to implement it so you can join if you want.

**Comment by Rajgupta36** [comment]
> This is duplicate of #73 I doubt any work has been done to implement it so you can join if you want.
Alright, I will work on it.
