### ISSUE TITLE
Populate GSoC 2020-2023 OWASP projects with respective custom tags

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#167]
This is a chore task to go through the OWASP site pages:
  - https://owasp.org/www-community/initiatives/gsoc/gsoc2020ideas
  - https://owasp.org/www-community/initiatives/gsoc/gsoc2021ideas
  - https://owasp.org/www-community/initiatives/gsoc/gsoc2022ideas
  - https://owasp.org/www-community/initiatives/gsoc/gsoc2023ideas
to gather participating project names and put them into JSON files the same way it was done [here](https://github.com/OWASP/Nest/commit/d26217231743a16b3cae2140738b12c1ce232660)

After it's done the `backend/data/project-custom-tags` should include gsoc-20[20-24].json files

**Comment by nitinawari** [comment]
"@arkid15r I have almost completed the task, but some projects, like Python Honeypot and Zed Attack Proxy (ZAP), are not available in the database by default. Should we add them to the JSON file ?

**Comment by arkid15r** [comment]
Yes, please add them too.

**Comment by nitinawari** [comment]
@arkid15r Please let me know if there are any mistakes or changes required.
