### ISSUE TITLE
Responsiveness irrespective of screen size

### ISSUE THREAD

**Issue by TenzDelek** [OWASP/Nest#168]
**Describe the bug**
Currently the cards are not suitable for mobile view
**To Reproduce**
1. Go to homepage
2. shrink the size of your window to match the phone view

**Expected behavior**
responsiveness all across the screen size
**Screenshots**
<img width="482" alt="image" src="https://github.com/user-attachments/assets/6d49a415-6ab7-4942-abdc-a74375c588b4" />

**Desktop (please complete the following information):**
 - Browser: Arc

**Smartphone (please complete the following information):**
 - Device: Iphone 13
 - Browser: Safari

**Additional context**

**Comment by arkid15r** [comment]
Hi @TenzDelek 
this is our old (temporary) frontend. Please check if the new one (TypeScript/React, see `/frontend`) has a room for UI improvemnet.
