### ISSUE TITLE
Feature: Added Pagination to project page

### ISSUE THREAD

**Issue by Rajgupta36** [OWASP/Nest#178]
### **current problem**
Currently, the application displays only 25 objects at a time, and we are unable to navigate through pages. If a user performs a search, the results are displayed with only 25 objects. However, there is no way to move to the next set of 25 objects (pagination is missing)
### **Describe the solution you'd like**

I want to add pagination. so that user can move from first 25 to another 25 objects through this bar.
![image](https://github.com/user-attachments/assets/bdf25926-6125-40e8-a04e-8b736d0f50fb)

#### **Tasks:**
1. Design the pagination UI (buttons, current page number).
2. Implement the pagination logic and link it with the data.
3. Fetch data dynamically based on the current page and items per page.

**Comment by Rajgupta36** [comment]
@arkid15r sir, after this we can implement the autocomplete feature in searchBar

**Comment by harsh3dev** [comment]
Hey this one is duplicate of #56 and I am already working on it.
@Rajgupta36

**Comment by Rajgupta36** [comment]
> Hey this one is duplicate of #56 and I am already working on it.
> @Rajgupta36 
Okk
