### ISSUE TITLE
Convert API JSON reponse snake case names to camel case for frontend

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#184]
Some AI generated input:

### 1. **TypeScript (Frontend) Convention: camelCase**
   - TypeScript and JavaScript widely follow the `camelCase` naming convention for variables and object properties.
   - Example:
     ```json
     {
       "totalPages": 10,
       "currentPage": 1,
       "itemsPerPage": 20
     }
     ```

### 2. **Python (Backend) Convention: snake_case**
   - Python developers typically use `snake_case` for variable names and dictionary keys.
   - Example:
     ```python
     response = {
         "total_pages": 10,
         "current_page": 1,
         "items_per_page": 20
     }
     ```

---

### Recommendation: **Convert snake_case to camelCase for the frontend**

To align with TypeScript conventions while keeping Python code clean, use **snake_case** internally in Python and convert to **camelCase** when sending the API response.

#### Example Implementation
You can automate this conversion using libraries like **`pydantic`** or **`inflection`**.

**Option 1: Manually convert**
```python
import json

def to_camel_case(snake_str):
    parts = snake_str.split('_')
    return parts[0] + ''.join(part.capitalize() for part in parts[1:])

def camel_case_keys(data):
    if isinstance(data, dict):
        return {to_camel_case(k): camel_case_keys(v) for k, v in data.items()}
    if isinstance(data, list):
        return [camel_case_keys(i) for i in data]
    return data

response = {
    "total_pages": 10,
    "current_page": 1,
    "items_per_page": 20
}

converted_response = camel_case_keys(response)
print(json.dumps(converted_response))  # {"totalPages": 10, "currentPage": 1, "itemsPerPage": 20}
```

**Option 2: Use `pydantic` for automatic conversion**
If you're using Pydantic for data validation, you can configure it to output camelCase:
```python
from pydantic import BaseModel

class Pagination(BaseModel):
    total_pages: int
    current_page: int
    items_per_page: int

    class Config:
        alias_generator = lambda x: ''.join(
            word.capitalize() if i else word for i, word in enumerate(x.split('_'))
        )
        allow_population_by_field_name = True

pagination = Pagination(total_pages=10, current_page=1, items_per_page=20)
print(pagination.json(by_alias=True))  # {"totalPages": 10, "currentPage": 1, "itemsPerPage": 20}
```

---

### Why This Approach?
1. **Backend remains Pythonic**: Your Python code stays clean and idiomatic (`snake_case`).
2. **Frontend-friendly**: The API response adheres to TypeScript/JavaScript conventions (`camelCase`).
3. **Scalability**: Automating the conversion ensures minimal manual work as the API grows.

This way, you can maintain consistency across your stack without compromising either side's conventions.

**Comment by Rajgupta36** [comment]
@AbhayTopno /assign is not working

**Comment by AbhayTopno** [comment]
How should I work on this

**Comment by yashpandey06** [comment]
@AbhayTopno  please ask @arkid15r   to assign it to you explicitly as we are migrating towards the project board approach now for managing tasks !

**Comment by yashpandey06** [comment]
@AbhayTopno let me know if I can take this up as I have the bandwidth to do now.

**Comment by AbhayTopno** [comment]
You can take this, since i haven't started yet 
@yashpandey06

**Comment by yashpandey06** [comment]
> You can take this, since i haven't started yet 
> @yashpandey06 


FYI : @arkid15r

**Comment by arkid15r** [comment]
I suggest extending Django http JsonResponse w/ the needed functionality and using it.

**Comment by arkid15r** [comment]
No longer needed.
