### ISSUE TITLE
Get indexed items total count from Algolia

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#185]
**Is your feature request related to a problem? Please describe.**
For consistency we want to get the total count of indexed items from the source -- Algolia.

**Describe the solution you'd like**
Create a one method to determine the total count of items for all entities (issue, project, chapter, committee). Cache the value for better performance. Name the field `total_items`. 

**Additional context**
Clean up the currently used method if they are no longer used.

**Comment by Rajgupta36** [comment]
Hii @arkid15r sir, I am familiar with Algolia. Can you assign this issue to me?

**Comment by yashpandey06** [comment]
@Rajgupta36 let me know if I can take this up ...I have a bandwidth to do it ...since you are already busy in paginations related stuff.
