### ISSUE TITLE
Enforce 'no-console': 'error' eslint rule

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#186]
**Is your feature request related to a problem? Please describe.**
Implement changes to enable `'no-console': 'error',` eslint rule

**Describe the solution you'd like**
Using console.* in prod is not a good practice. We need to clean up existing cases and enable the rule to enforce it.

**Comment by yashpandey06** [comment]
@arkid15r can you assign this to me ? as this includes minor changes only ?
