### ISSUE TITLE
Prepare the new frontend for staging environment

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#191]
**Is your feature request related to a problem? Please describe.**
Once we're done w/ migration to the new frontend we'll need to run it within our [docker-compose-staging.yaml ](https://github.com/OWASP/Nest/blob/0629eba2aec1e1742431cde3e155cebaa32cafa4/docker-compose-staging.yaml) stack. We currently have some content in the [Dockerfile.staging](https://github.com/OWASP/Nest/blob/0629eba2aec1e1742431cde3e155cebaa32cafa4/frontend/Dockerfile.staging) but it has never been tested/used.

**Describe the solution you'd like**
Revisit Dockerfile.staging for the new frontend and modify/improve if needed. Update docker-compose-staging.yaml to include the new frontend in staging environment

**Comment by harsh3dev** [comment]
I want to attend to this issue.
Kindly assign this to me.
Thanks
