### ISSUE TITLE
Fix responsiveness of Header for Mobile

### ISSUE THREAD

**Issue by harsh3dev** [OWASP/Nest#210]
**Describe the bug**
The current Header is not responsive yet.

**Expected behavior**
To include a hamburger menu for mobile phone displaying all the navitems

**Screenshots**
![image](https://github.com/user-attachments/assets/e7315f50-5bb8-41b4-abbb-9b3631be58a8)

**Smartphone (please complete the following information):**
 - Device: Phone
 - OS: Android
 - Browser Chrome
 - Version latest

**Comment by yashpandey06** [comment]
/ assign is not working anymore ...if I am not worng !

**Comment by harsh3dev** [comment]
@yashpandey06 yes i know that.
