### ISSUE TITLE
Chapters page social links same key error

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#213]
**Describe the bug**
<img width="1447" alt="Screenshot 2024-12-19 at 4 13 59 PM" src="https://github.com/user-attachments/assets/52fac081-b642-49f5-b253-b7119cbc43a2" />

**To Reproduce**
http://localhost:3000/chapters

**Expected behavior**
No error

**Comment by TenzDelek** [comment]
I would love to take on this too cc @arkid15r
