### ISSUE TITLE
Add last update date to Chapters page

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#216]
**Is your feature request related to a problem? Please describe.**
We don't show any metadata for chapters at the moment
<img width="1180" alt="Screenshot 2024-12-19 at 4 20 58 PM" src="https://github.com/user-attachments/assets/18b596a0-4c33-422b-b9cc-b04b5d1c4b33" />

**Describe the solution you'd like**
Add last updated date similar to Committees

**Comment by yashpandey06** [comment]
@arkid15r please assign this to me
