### ISSUE TITLE
Fix: 'Contribute' Button Redirection on Project page in the frontend

### ISSUE THREAD

**Issue by ShashaankS** [OWASP/Nest#227]
**Is your feature request related to a problem? Please describe.**
Currently, the "Contribute" button on the project cards is currently redirecting to the homepage instead of directing users to the specific GitHub repository for the respective project. This can be cumbersome for users who want to contribute directly.

**Describe the solution you'd like**

- This can be done by modifying _handleButtonClick_ function in Projects.tsx, fetching the respective project_name and redirecting to respective github repo.

- Also `api /api/v1/owasp/search/project` doesn't have the _project_url_ attribute which can be available from `/api/v1/owasp/search/issue`

- But it requires a search in the issues api to get atleast one issue and modidy the _idx_project_url_ attribute to get github url removing the `issues/<number>`

Please share your thoughts or suggestions for additional features that can improve this implementation.

**Comment by Naveen-Pal** [comment]
Hii @ShashaankS ,
As I can see that the "Contribute" button on project is not redirecting to the home page instead it is redirecting to the contribute page and showing the issues of that projects and all the issue in that page are redirecting to corresponding Github issue page. <br/> <br/> Do you mean there should be button for user to directly access the github repository of that project?

![image](https://github.com/user-attachments/assets/db237e9f-b89c-4439-929b-eeacba27ce44)
![image](https://github.com/user-attachments/assets/62605531-05e3-4e62-bce0-5e4fefaf78e8)

**Comment by ShashaankS** [comment]
@Naveen-Pal Okay I see.
But are we not using the frontend server ?

**Comment by arkid15r** [comment]
> @Naveen-Pal Okay I see. But are we not using the react typescript server ?

We've been migrating to the new TypeSceript/React frontend. You need to look at the code under `/frontend` directory

**Comment by ShashaankS** [comment]
@arkid15r should I proceed with the implementation in the frontend dir ?

**Comment by arkid15r** [comment]
> @arkid15r should I proceed with the implementation in the frontend dir ?

Yes, all contributors work w/ the new FE.
What are you going to implement?

**Comment by ShashaankS** [comment]
]
[Screencast from 12-22-2024 01:58:13 AM.webm](https://github.com/user-attachments/assets/c6aa0587-313a-4fe5-877d-634f9e038db0)

This is what i encountered in the new FE with the contribute button, if we require a issues dedicated page for each project as in the currently deployed website then we can do that and other option which i suggested is mentioned on the first comment.
Please share if any suggestions which can improve this implementation.

**Comment by arkid15r** [comment]
@ShashaankS it's working as intended as we don't have neither Contribute page. It'll be done within couple days (@harsh3dev has been working on it)
