### ISSUE TITLE
Redirect Nest home to projects page

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#229]
**Describe the solution you'd like**
Add temporary redirect from `/` to `/projects` page similar to the [old FE](https://github.com/OWASP/Nest/blob/main/backend/apps/owasp/views/home.py#L12).

**Comment by nitinawari** [comment]
@arkid15r  Assign to me

**Comment by ShashaankS** [comment]
@arkid15r assign it to me.

**Comment by arkid15r** [comment]
assigned to @nitinawari (first commented)
