### ISSUE TITLE
Make frontend Header sticky on the page

### ISSUE THREAD

**Issue by kasya** [OWASP/Nest#232]
**Is your feature request related to a problem? Please describe.**
When we scroll on the page with many items we have to scroll all the way up to get to a different page (e.g. Projects -> Chapters).

**Describe the solution you'd like**
Making Header component sticky on the page will help with navigation between pages.

**Comment by nitinawari** [comment]
Assign to me @kasya

**Comment by Tusharjamdade** [comment]
Hi @kasya and @nitinawari,
I am currently working on the PR for the responsive header. I am almost done and can add the functionality to make it sticky at the top.

**Comment by arkid15r** [comment]
I guess you could do that @Tusharjamdade
Thank you.

@nitinawari just FYI if you've already started working on it

**Comment by nitinawari** [comment]
@arkid15r  yes , i completed this

**Comment by nitinawari** [comment]
@arkid15r  @Tusharjamdade Sorry for this; I was not aware of it. I have completed the task and created a PR. i saw meeseges after PR raised
