### ISSUE TITLE
Take care of the `Unexpected any` warning

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#235]
**Describe the bug**

```bash
/home/owasp/src/lib/hooks/useSearchPage.ts
  48:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 1 problem (0 errors, 1 warning)
```

**Expected behavior**
No warning (either addressed or suppressed)

**Comment by TenzDelek** [comment]
Would like to take on this cc @arkid15r

**Comment by TenzDelek** [comment]
hey @arkid15r , what command is that to test that out

**Comment by arkid15r** [comment]
> hey @arkid15r , what command is that to test that out

make check (it's eslint warning)
