### ISSUE TITLE
Implement simple chapter/committee/project details page

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#236]
This example considers projects only but the task is to implement it for all chapters/committees/projects

**Is your feature request related to a problem? Please describe.**
Currently we have a page with the list of projects. There is no dedicated pages for each project.

**Describe the solution you'd like**
Create a page at `/projects/<project-key>` location that includes basic project info. For now it can reuse existing `Card` component with the project info we currently have.

**Comment by Rajgupta36** [comment]
can i work on it @arkid15r

**Comment by ShashaankS** [comment]
@arkid15r can you assign this to me

**Comment by arkid15r** [comment]
Folks, you have some work to do w/ Algolia, right? :)

When those are done you can try this one again if it's still available. My goal is to have tasks for everyone willing to contribute.

**Comment by nitinawari** [comment]
@arkid15r assign it to me

**Comment by arkid15r** [comment]
Hi @nitinawari,
do you need help with this task? We can split it to 3 smaller items and/or re-assign. Please let me know.

**Comment by nitinawari** [comment]
@arkid15r, I think I need help. I haven't started working on it until now because I'm stuck on the error-handling issue. Maybe I'll be able to complete both today, or you could split it into three smaller assignments instead.

**Comment by arkid15r** [comment]
Okay, let's give a chance to someone else to work on it while you're busy. I'm not sure if splitting is a good idea as the tasks are very similar.

**Comment by Rajgupta36** [comment]
can i do it @arkid15r

**Comment by Rajgupta36** [comment]
i think dialog component is good for that

**Comment by arkid15r** [comment]
Do you mean a modal?

This may be a good idea if we don't want user to switch pages and stay on the project list page but in this task we want a separate page for each entity. Think of it as project/chapter/etc page with all related information.

**Comment by nitinawari** [comment]
@arkid15r  I apologize for not completing the task on time and causing an increase in your headache. I will ensure that I complete tasks on time in the future.

**Comment by Rajgupta36** [comment]
> Do you mean a modal?
> 
> This may be a good idea if we don't want user to switch pages and stay on the project list page but in this task we want a separate page for each entity. Think of it as project/chapter/etc page with all related information.

I mean a component that appears as a popup on the same page, showing details. If the user wants more information, we can redirect them to another separate page via a button (e.g., 'More Info' or something else)

**Comment by harsh3dev** [comment]
@arkid15r I would like to work on the other pages like `chapters/:id` or `committees/:id`

**Comment by Rajgupta36** [comment]
> @arkid15r I would like to work on the other pages like `chapters/:id` or `committees/:id`

@harsh3dev this is a combine task for all pages

**Comment by yashpandey06** [comment]
Can I work on it @arkid15r ?

**Comment by harsh3dev** [comment]
If we implement it part wise then the work would be fast. @Rajgupta36 
But if you can do it all b yourself then its okay.

**Comment by arkid15r** [comment]
@Rajgupta36 yeah, popup is not what this task is about. As @harsh3dev mentioned, I mean having chapters/:id or committees/:id projects/:id handlers implemented. Or maybe I don't understand why popups would be more preferable here.

**Comment by Rajgupta36** [comment]
> @Rajgupta36 yeah, popup is not what this task is about. As @harsh3dev mentioned, I mean having chapters/:id or committees/:id projects/:id handlers implemented. Or maybe I don't understand why popups would be more preferable here.

okay

**Comment by arkid15r** [comment]
> If we implement it part wise then the work would be fast. @Rajgupta36 But if you can do it all b yourself then its okay.

I see what you mean @harsh3dev, these 3 pages will have pretty much the same structure and it may be more beneficial to get it implemented by one person.
