### ISSUE TITLE
Make Algolia requests for Chapters page directly from FE

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#237]
**Is your feature request related to a problem? Please describe.**
At the moment all requests to Algolia go from FE to BE and then to Algolia index engine.

**Describe the solution you'd like**
Implement logic for the Chapters page to request data from Algolia right from FE (w/o sending it to BE first)

**Additional context**
https://www.algolia.com/doc/libraries/javascript/v5/

**Comment by ShashaankS** [comment]
I would like to work over it @arkid15r

**Comment by yashpandey06** [comment]
@arkid15r seems interesting should I take it ?...let me know if any other contributor is interested in it !

**Comment by arkid15r** [comment]
We're going to start enforcing the 2 tasks per person rule I mentioned last week.

You're welcome to take this one after you're done with your current tasks -- https://github.com/orgs/OWASP/projects/43/views/1?filterQuery=-status%3ADone+assignee%3Ayashpandey06

**Comment by Naveen-Pal** [comment]
Hii @arkid15r, 
I am interested. 
can you please assign it to me.
