### ISSUE TITLE
Make Algolia requests for Projects page directly from FE 

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#239]
**Is your feature request related to a problem? Please describe.**
At the moment all requests to Algolia go from FE to BE and then to Algolia index engine.

**Describe the solution you'd like**
Implement logic for the Projects page to request data from Algolia right from FE (w/o sending it to BE first)

**Additional context**
https://www.algolia.com/doc/libraries/javascript/v5/

**Comment by ShashaankS** [comment]
@arkid15r Assign this issue to me
