### ISSUE TITLE
Make Algolia requests for Committees page directly from FE 

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#240]
**Is your feature request related to a problem? Please describe.**
At the moment all requests to Algolia go from FE to BE and then to Algolia index engine.

**Describe the solution you'd like**
Implement logic for the Committees page to request data from Algolia right from FE (w/o sending it to BE first)

**Additional context**
https://www.algolia.com/doc/libraries/javascript/v5/

**Comment by ShashaankS** [comment]
@arkid15r these all are similar issues, solution can be implemented on all these l, with some tweaks

**Comment by Rajgupta36** [comment]
@arkid15r , assign this to me

**Comment by arkid15r** [comment]
> [@arkid15r](https://github.com/arkid15r) these all are similar issues, solution can be implemented on all these l, with some tweaks

You're 100% right. My goal here is involve more contributors into Algolia search. It's a big part of OWASP Nest project.
