### ISSUE TITLE
Implement NestBot endpoints to support events handling horizontal scaling

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#241]
**Is your feature request related to a problem? Please describe.**
Currently NestBot uses Socket mode for all environments. It's really convenient for development environment due to simplified bot events handler run locally. However, the Socket mode approach has its drawbacks in terms of scalability (https://api.slack.com/apis/event-delivery)

<img width="1085" alt="Screenshot 2024-12-22 at 11 42 12 AM" src="https://github.com/user-attachments/assets/4c502216-e518-43a9-bd6d-f8e02df271ba" />

**Describe the solution you'd like**
Create new OWASP Nest endpoints that would replicate (reuse the code) existing Slack slash commands and event handlers.
We still want use Socket mode for local environment.

**Additional context**
  - https://api.slack.com/concepts
  - https://api.slack.com/apis/events-api
  - https://api.slack.com/apis/event-delivery

**Comment by ShashaankS** [comment]
@arkid15r I will do this, this should be new but interesting

**Comment by arkid15r** [comment]
> @arkid15r I will do this, this should be new but interesting

Yeah, it seems it aligns w/ your Django learning goals. I lowered the priority to `P3` so you can work on it in background while having some room for higher priority tasks.

Thank you @ShashaankS

**Comment by ShashaankS** [comment]
Hey @arkid15r,
I explored Slack API documentation, did some increments on the source to get things done
Tested things on a test channel and test bot
![Screenshot from 2024-12-25 20-39-48](https://github.com/user-attachments/assets/0b753e61-5015-487d-b06a-3815610b587f)
this will be the endpoint : https://nest.owasp.dev/slack
![Screenshot from 2024-12-25 20-47-23](https://github.com/user-attachments/assets/8d5dedb7-2624-4067-adc3-ee4aa4f807f5)


Please suggest how can i test it more, share suggestions

**Comment by ShashaankS** [comment]
Also, there is provision if `DJANGO_SLACK_CONFIGURATION` is set to `Local` then websocket can also be used.

**Comment by arkid15r** [comment]
@ShashaankS this is looking good!
Please create a PR for the code review and suggestions -- we'll need to change the endpoint path and maybe something else.

Thank you!
