### ISSUE TITLE
Refactor frontend to use absolute imports

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#253]
**Is your feature request related to a problem? Please describe.**

> I've been reviewing some frontend PRs recently and noticed frequent use of `../../../` in TypeScript imports. Is there a more efficient or cleaner way to handle these relative imports, especially for deeply nested files? Hopefully, for both tests and the source code:

![image](https://github.com/user-attachments/assets/acc8ca94-819d-498e-a5ff-ad3673a3073b)

**Describe the solution you'd like**
Refactor both frontend code and its tests to use absolute imports w/o `../../../`.

**Comment by yashpandey06** [comment]
@arkid15r I can look for this ...please assign ..
Thanks !
