### ISSUE TITLE
Clean up `owasp/api/search` endpoints

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#254]
**Is your feature request related to a problem? Please describe.**
After migrating search to FE we don't need BE search endpoints.

**Describe the solution you'd like**
Make sure they are 100% unused, clean up the code and related tests.

**Comment by yashpandey06** [comment]
@arkid15r please assign this to me !

**Comment by arkid15r** [comment]
I can only assign tasks from "Todo" section -- https://github.com/orgs/OWASP/projects/43/views/3

**Comment by Yashgupta9330** [comment]
@arkid15r can you assign it to me ?

**Comment by yashpandey06** [comment]
@Yashgupta9330 it is the is not  in todo section for current  iteration as per arkid.

**Comment by ShashaankS** [comment]
I'll work on it, please assign this to me @arkid15r
