### ISSUE TITLE
Fix FE suggestion

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#260]
**Is your feature request related to a problem? Please describe.**
`nest-frontend  | Instead of /public/img/owasp_icon_white_sm.png, use /img/owasp_icon_white_sm.png.`

**Describe the solution you'd like**
Use it in the suggested way

**Comment by yashpandey06** [comment]
@arkid15r please help assign this to me ..

Thanks !

**Comment by arkid15r** [comment]
Probably fixed in https://github.com/OWASP/Nest/commit/31626655b0cb5ea68ccbcc9f4bbb874496c6b83c
