### ISSUE TITLE
Clean up owasp/templates/search frontend

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#267]
**Is your feature request related to a problem? Please describe.**
After migrating to the new FE we no longer need the old one

**Describe the solution you'd like**
Remove https://github.com/OWASP/Nest/tree/main/backend/apps/owasp/templates/search files

**Comment by TenzDelek** [comment]
Would love to do it cc @arkid15r

**Comment by yashpandey06** [comment]
Please help assign this to me @arkid15r

**Comment by bhagyashree980** [comment]
Hii @arkid15r ,Please assign this issue to me i'll do this.

**Comment by arkid15r** [comment]
@TenzDelek @bhagyashree980 this is a backlog item. I can only assign tasks from [Todo section](https://github.com/orgs/OWASP/projects/43/views/2), sorry.
