### ISSUE TITLE
Enforce no unused imports rule

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#281]
**Is your feature request related to a problem? Please describe.**
Some files import components but never use them. See example [here](https://github.com/OWASP/Nest/blob/86956665ea022598d428c8febdd6eb57a41c9fad/frontend/__tests__/src/pages/Chapters.test.tsx#L2).

**Describe the solution you'd like**
Make sure eslint catches this imports and fires an error for them

**Comment by Rajgupta36** [comment]
can i work on this issue , @arkid15r

**Comment by arkid15r** [comment]
Any success on this one?

**Comment by Rajgupta36** [comment]
This issue is related to the React import statement only. ESLint isn't able to catch this issue when JSX tags are used. I found a command to fix this, but not any rule yet

**Comment by Rajgupta36** [comment]
This issue is related to the React import statement only. ESLint isn't able to catch this issue when HTML tags are used. I found a command to fix this, but not any rule yet
