### ISSUE TITLE
Consolideate .gitignore files

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#286]
**Is your feature request related to a problem? Please describe.**
We have 2 .gitignore files: 1 at the projects' root directory (original backend gitignore file) and another in `frontend` directory

**Describe the solution you'd like**
Consolidate .gitignore rules into 1 file located in projects' root while keeping all rules in place (update paths where needed). Make sure there is no duplicate rules.

**Comment by Tusharjamdade** [comment]
@arkid15r  I can take this up. Please assign it to me.
