### ISSUE TITLE
Chapters page (frontend)

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#29]
We currently have most of the Chapters page BE functionality ready. The endpoint for chapter search is available at [`api/v1/owasp/search/chapter`](https://nest.owasp.dev/api/v1/owasp/search/chapter). It currently provides 
```
"idx_created_at",
"idx_leaders",
"idx_name",
"idx_related_urls",
"idx_summary",
"idx_tags",
"idx_updated_at",
"idx_url",

```
 fields. The results are ranked based on the proximity to the user's location.

I'd like the new page layout be consistent with [Projects page](https://nest.owasp.dev/projects/) (name, leaders, summary, tags) with some extra icons (font awesome) for the related URLs based on the link platform type (show YouTube icon for youtube.com... links, LinkedIn icon for linkedin.com links, Twitter icon for twitter.com/x.com link, etc -- the real challenge here is compiling a list of platforms we want to cover).
The button should be labeled as `Join` and have a link to the chapter's `idx_url`.

I'd be happy to help w/ any questions here or in the #project-nest Slack channel.

**Comment by arkid15r** [comment]
Hi @VedmaPranav any updates on this?

Let me know if you need some help.

**Comment by VedmaPranav** [comment]
Hey @arkid15r 
I am working on it and should be able to open a PR by this weekend
