### ISSUE TITLE
Add relevant URLs to the Footer Links

### ISSUE THREAD

**Issue by harsh3dev** [OWASP/Nest#290]
**Is your feature request related to a problem? Please describe.**
Currently some of the links in the footer are not updated yet.
![image](https://github.com/user-attachments/assets/41c25b87-e237-4a85-b347-dec0b73467dc)

**Describe the solution you'd like**
To update all the links with the correct URLs

**Additional context**
Here are the URLs I have gathered from OWASP website to update them

- Our mission : https://owasp.org/about/
- Team : https://owasp.org/corporate/#
- Careers: https://owasp.org/careers/

---

- Contribute: https://nest.owasp.dev/projects/contribute/
- Projects: https://owasp.org/projects/
- Chapters: https://owasp.org/chapters/

---

- Committees: https://owasp.org/committees/
- Events: https://owasp.org/events/
- Forum: https://owasp.org/www-community/

---

- Locations: https://www.meetup.com/pro/owasp/
- Support: https://owasp.org/donate/
- Contact us: https://owasp.org/contact/

**Comment by harsh3dev** [comment]
@arkid15r Please assign me this one if we are ready to work on this.

**Comment by yashpandey06** [comment]
@arkid15r can I work on this ?

**Comment by arkid15r** [comment]
@harsh3dev yes, footer component needs some improvement. I think you have a good vision on this. I just would like to add some Nest related links, like our Slack, maybe GitHub repo. It should be done in a way it's not confused w/ OWASP organization in general. Let's sort it out on the review phase. 

Thanks for adding this!
