### ISSUE TITLE
Implement production release process

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#295]
**Is your feature request related to a problem? Please describe.**
Our automated pipeline currently deploys to the staging environment at nest.owasp.dev. As the project evolves, it's time to establish a dedicated production environment for nest.owasp.org, which currently redirects to staging.

**Describe the solution you'd like**
Enhance CI/CD workflows, Docker configurations, Ansible playbooks, and any other necessary setups to enable automated deployments to the Nest production environment triggered by creating a GitHub release.

**Comment by yashpandey06** [comment]
So as per my understanding the deployments needs to be handled via deploy.yml using ansible , currently it's done via pipeline yml file using manual push to do it .


Seems  interesting...let me know when this  task is out of the backlog I would be happy to take it .@arkid15r

**Comment by yashpandey06** [comment]
Also don't we have a pr labeler for that ...something like Devops / deploy?

**Comment by arkid15r** [comment]
We have working setup for staging so the task is to replicate docker image build and deployment parts for production environment. The only difference will be the trigger -- we want to do it upon release publishing event.

>Also don't we have a pr labeler for that ...something like Devops / deploy?

Those are for PRs.
