### ISSUE TITLE
Implement light/dark theme support for legacy project/contribute pages

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#3]
https://getbootstrap.com/docs/5.3/customize/color-modes/

**Comment by onass1** [comment]
I intend to take this issue, I will try to solve it, I'm going to read steps from the AI generated steps on new nest site and can I contact with you If I'd faced issues? As this is my first contribution tho.

**Comment by arkid15r** [comment]
Hi @onass1 
You can use this thread or alternatively if you use OWASP Slack feel free to join out #project-nest channel

**Comment by VedmaPranav** [comment]
Hey @arkid15r 
If no one is working on this issue, can you assign it to me?

**Comment by arkid15r** [comment]
Sure, thank you @VedmaPranav
