### ISSUE TITLE
Show the total number of chapters on the /chapters page

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#38]
Implement it the same way it's done for `/projects` (https://github.com/OWASP/Nest/pull/11) and `/projects/contribute` (https://github.com/OWASP/Nest/pull/32) pages.

The search bar placeholder text should be `Search through {chaptersCount} chapters around the world`

**Comment by ShashaankS** [comment]
Hi @arkid15r ,

I hope this message finds you well. I’m a new contributor to the project, and I’m interested in working on this issue as a "good first issue'. I will be editing the chapter model and add a api endpoint to fetch the real-time chapters.

Could you please assign it to me? I’m eager to get started and contribute!

**Comment by arkid15r** [comment]
Hi @ShashaankS 
it's yours! You could also use `/assign` command to get it assigned to you automatically.

Thank you for taking care of that!

**Comment by ShashaankS** [comment]
Hi @arkid15r,
i am getting a lot of error populating the db with angolia, since i am based in INDIA, is there some other way to do so or its some other problem

**Comment by arkid15r** [comment]
We've seen this before and it seemed to be related to a slow internet connection. You can try this workaround: run `make shell` and then run `poetry run python manage.py algolia_reindex --batchsize 100`
The key difference here is the `--batchsize` option.

I hope this helps.

**Comment by arkid15r** [comment]
@ShashaankS any updates on this? Do you need help with it?

**Comment by ShashaankS** [comment]
i have made the required changes to the code referencing the the #11 , and made a PR, hope it does the needful.
Looking forward for any changes or so.
