### ISSUE TITLE
Twitter handles point to GitHub

### ISSUE THREAD

**Issue by bendehaan** [OWASP/Nest#5]
Love the project!

Minor nit: for Jeroen and me our Twitter/X handles are mentioned on WrongSecrets, but they point to (non-existing) GitHub handles. The correct ones are @commjoen and @bendehaan. Could you fix this (or point me to where we could fix it)?

**Comment by arkid15r** [comment]
Thanks for the feedback @bendehaan !

I've removed the special handling of items starting with "@" so far. 

You can control this content for your project [here](https://github.com/OWASP/www-project-wrongsecrets/blob/main/leaders.md)
