### ISSUE TITLE
Implement pagination for `Contribute` page

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#50]
Currently `/projects/contribute` page shows top 25 results for any query. The Algolia search engine supports pagination but it hasn't been implemented on the backend.

The task consists of 2 parts: 
  - implement search results pagination on the backend (extend `search::issue::get_issues` [method](https://github.com/OWASP/Nest/blob/31be56ef5d0bf727a70e751d7a0c6b1dfb51d2ea/backend/apps/owasp/api/search/issue.py#L13) to support `page` parameter)
  - add pagination support on the frontend

Documentation references:
  - https://www.algolia.com/doc/api-reference/api-parameters/page/

**Comment by arkid15r** [comment]
After `Contributions` pagination support is implemented it needs to be extended to other pages with multiple page entity lists (`Projects` and `Chapters` pages)

**Comment by harsh3dev** [comment]
Hi, I have started to work on this issue.
@arkid15r 
Please assign this to me

**Comment by arkid15r** [comment]
We want to focus on the new frontend. Closing this one.
