### ISSUE TITLE
Implement header component

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#53]
The component should be responsible for rendering the Nest navbar:

<img width="1738" alt="Screenshot 2024-11-03 at 9 43 33 AM" src="https://github.com/user-attachments/assets/b3e3734e-e623-4159-bb7b-91280a091de7">

The currently used code is located here https://github.com/OWASP/Nest/blob/31be56ef5d0bf727a70e751d7a0c6b1dfb51d2ea/backend/templates/base.html#L33

For simplicity we can focus on just replicating the current look with TypeScript/React for now.

**Comment by kasya** [comment]
I'm taking this one! 💯

**Comment by arkid15r** [comment]
Thank you @kasya
