### ISSUE TITLE
Implement reusable OWASP entity component

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#54]
The Nest app has four main pages: Contribute, Projects, Chapters, and Committees. Each page is different, but we can display their information in a similar style.

To make the code cleaner and ensure a consistent look across the site, we want to create one component that displays items on all pages. This component should be flexible, showing specific details based on what is passed to it. For example, tags or labels should appear on the Contribute and Projects pages, but not on the Chapters or Committees pages.

**Comment by harsh3dev** [comment]
For this issue:
1. we need to create a card component which will display the information and it can be used in all the pages
2. It will be dynamic, based on the props that we pass onto it; It will display the relevant information 
I am ready to work on this issue

**Comment by harsh3dev** [comment]
We will have to develop a card component which will 
1. show the information based on the props we pass
2. a container that will render all the cards
3. When the card is clicked it should perform the necessary actions like opening the modal
4. The card will dynamically show content and other details based on the props passed to it.
I am ready to work on this issue

**Comment by arkid15r** [comment]
This issue it major one, I'm glad you want to work on it. @harsh3dev don't hesitate to reach out to me in Slack as there might be a lot of decisions to make during the implementation.

Assigning it to you, thank you!

**Comment by arkid15r** [comment]
Implemented in #72 by @harsh3dev
