### ISSUE TITLE
Implement reusable search component

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#55]
Like the approach for [a shared component for all items](https://github.com/OWASP/Nest/issues/54), we want a search bar that works across all pages (Contribute, Projects, Chapters, and Committees).

This search bar should be flexible and configurable, allowing it to connect with the backend and provide the right search features for each page.

**Comment by Yashgupta9330** [comment]
I want to work on this issue can you please assign me this issue?

**Comment by arkid15r** [comment]
You got it

**Comment by tsu-ki** [comment]
@Yashgupta9330 Are you still working on this issue? I noticed that you've also assigned yourself another issue(https://github.com/OWASP/Nest/issues/68). So, if you aren't working on this, then I'd like to take over

**Comment by Yashgupta9330** [comment]
I have made the changes and am waiting for the Django PR to be merged so that I can test it.

**Comment by arkid15r** [comment]
> I have made the changes and am waiting for the Django PR to be merged so that I can test it.

Hey @Yashgupta9330 what PR blocks you (not sure if it's something I can help you with)?

**Comment by Yashgupta9330** [comment]
To make API calls, we first need to resolve the CORS issue in Django.

**Comment by arkid15r** [comment]
Gotcha! Yes, I've reviewed https://github.com/OWASP/Nest/pull/100 and waiting for the comments to be addressed. I hope it'll be merged today.

You can also reference the PRs in your issue replies as a blockers. That'd save some time for us.

**Comment by arkid15r** [comment]
@Yashgupta9330 just FYI -- the https://github.com/OWASP/Nest/pull/100 has been merged.

**Comment by arkid15r** [comment]
Hi @Yashgupta9330, are you still working on this? Please free up any issues you don't work on (if any).
Thank you!
