### ISSUE TITLE
Implement reusable pagination component

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#56]
Like the approach for [a shared component for all items](https://github.com/OWASP/Nest/issues/54), we want a pagination component that works across all pages (Contribute, Projects, Chapters, and Committees).

This pagination component should be flexible and configurable, allowing it to connect with the backend and provide the right pagination features for each page.

**Comment by harsh3dev** [comment]
I am already making the pagination for the project/contribute page.
I can work on this issue, just few question:
Do I need to make it in the existing code or in React/Typescript?

**Comment by Rajgupta36** [comment]
Are u creating it for vue and django frontend or react frontend ?

**Comment by harsh3dev** [comment]
@Rajgupta36 
I have implemented the backend for this one for which I will make a PR soon.
you can start working on the frontend (React + TS) for this if you want thanks.
/unassign

**Comment by arkid15r** [comment]
We have only BE part implemented and the issue was closed automatically as it had been linked to that PR.
Reopening it.
