### ISSUE TITLE
Implement Project Routing with React Router

### ISSUE THREAD

**Issue by harsh3dev** [OWASP/Nest#75]
Set up and implement routing in the project using `react-router-dom` to enable smooth navigation across various components and pages. This setup will enhance the project's structure, support dynamic routes, and allow for future route expansion.

---

#### **Requirements**:
1. **Library**: Use `react-router-dom`.
2. **File Structure**:
    - Maintain a modular file structure for routes. If necessary, create dedicated files for complex routes (e.g., `DashboardRoutes.js`).
3. **Navigation**:
    - Use `Link` or `NavLink` components for navigation to enhance single-page app functionality.
4. **Code Splitting (Optional)**:
    - Use `React.lazy()` and `Suspense` to load components on demand, especially for larger pages like `Dashboard`.
5. Ensure 404 handling to improve the user experience on undefined paths.

---

**Comment by AbhayTopno** [comment]
Are you doing it yourself? If not, you could assign it to me.

**Comment by harsh3dev** [comment]
> Are you doing it yourself? If not, you could assign it to me.

@AbhayTopno Please self assign this to yourself
