### ISSUE TITLE
Implement all the Pages for the frontend.

### ISSUE THREAD

**Issue by harsh3dev** [OWASP/Nest#86]
Since the  **Header**, **Footer**, and the **Entity Component** are almost implemented and the basic setup is done.
It is time to implement the various pages so that further work can be done on each one.
![image](https://github.com/user-attachments/assets/18500d93-55e0-4150-b1d6-c4fe61d13411)

Steps to implement:
- To create new pages for each of the `Contribute`, `Projects`, `Committee`, `Chapters`
- To fetch the API data from the backend, show the entity card on each page.

Related issues:
  - #88 
  - #89 
  - #90 
  - #91

**Comment by harsh3dev** [comment]
Its better to work on individual issues

**Comment by harsh3dev** [comment]
@arkid15r Shall this one be closed now?

**Comment by arkid15r** [comment]
Let's close it after https://github.com/OWASP/Nest/issues/251 is implemented

**Comment by harsh3dev** [comment]
Sure I will implement it latest by tonight.
