### ISSUE TITLE
Migrate Contribute page to the new frontend

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#88]
As per https://github.com/OWASP/Nest/issues/86 but focusing on `/projects/contribute` page only

**Comment by yashpandey06** [comment]
@arkid15r  I see no one is assigned for this task , let me know if i can take up this .

**Comment by harsh3dev** [comment]
@yashpandey06 are you working on this?
Please use self assign command to assign this to yourself. e.g: (slash)assign
Thanks

**Comment by yashpandey06** [comment]
> @yashpandey06 are you working on this?
> Please use self assign command to assign this to yourself. e.g: (slash)assign
> Thanks

Yeah

**Comment by arkid15r** [comment]
Any updates on this one? We're half-way done, waiting for this one and Chapters to complete.

**Comment by yashpandey06** [comment]
@arkid15r facing some issues in the card component thing that I ask about trying to fix it asap !

**Comment by yashpandey06** [comment]
@AbhayTopno showing willingness to take up this task ! will get back to you asap

**Comment by Yashgupta9330** [comment]
@AbhayTopno are you working on this?

**Comment by AbhayTopno** [comment]
Yes, I am

**Comment by AbhayTopno** [comment]
@harsh3dev i have unassigned myself,  you can work on it on

**Comment by AbhayTopno** [comment]
@harsh3dev i have unassigned myself , now you can work on it

**Comment by harsh3dev** [comment]
@arkid15r kindly assign me this issue.
