### ISSUE TITLE
Migrate Chapters page to the new frontend

### ISSUE THREAD

**Issue by arkid15r** [OWASP/Nest#90]
As per https://github.com/OWASP/Nest/issues/86 but focusing on `/chapters` page only

**Comment by tsu-ki** [comment]
@arkid15r Can I work on this issue? I've almost completed the my assigned issue and have requested a review on our slack conversation

**Comment by arkid15r** [comment]
@tsu-ki did you have a chance to work on it?

**Comment by tsu-ki** [comment]
@arkid15r yes, i'm halfway done with it. I'll need a couple of more days to complete it, but I'll try to be as quick as possible. thank you for checking up on me!

**Comment by arkid15r** [comment]
Has any progress been done towards completing this? We have a milestone that depends on it.

**Comment by tsu-ki** [comment]
@arkid15r I'm working on it right now and got stuck with a problem, I've have asked @harsh3dev for help as he's already implemented `/Projects` pages and I'll submit a PR for the same over this weekend. I sincerely apologise for the inconsistency in my work.

**Comment by harsh3dev** [comment]
Is no one attending to this issue?
@arkid15r 
I can implement this if no one has worked on it.
Please let me know.

**Comment by arkid15r** [comment]
@harsh3dev  yes, I believe the issue is pretty straigh-forward but it is P1.
Please feel free to contribute the code as you have it done for Chapters recently

**Comment by harsh3dev** [comment]
Sure, I will be raising the PR tomorrow.
