### ISSUE TITLE
Proposal: Discuss Adding Unit Tests Alongside Frontend Migration to React and TypeScript

### ISSUE THREAD

**Issue by yashpandey06** [OWASP/Nest#93]
## Description  
As the team is currently migrating the frontend to React and TypeScript, I would like to propose a discussion around incorporating unit tests as part of this migration process.  

## Why This is Important  
- **Opportunity to Build a Strong Foundation:** Since new pages and components will be introduced during the migration, this is an ideal time to integrate unit tests. It ensures that the new code is robust and maintainable from the start.  
- **Improved Code Quality:** Unit tests will help catch bugs early in the development cycle, reducing the risk of regressions and improving overall code quality.  
- **Long-Term Benefits:** Establishing a culture of writing unit tests now will make future development smoother and more reliable.  

## Proposed Approach  
- Use a preferred unit testing library (e.g., Jest, React Testing Library, etc.) to write tests for the new components and pages.  
- Discuss and finalize the testing strategy and library in a dedicated Slack channel to ensure alignment across the team.  

## Next Steps  
1. Initiate a discussion in the Slack channel to gather input from the team on the preferred testing library and approach.  
2. Align on a strategy for writing unit tests alongside the migration process.  
3. Document the agreed-upon approach for consistency moving forward.  

Let’s use this opportunity to not only modernize the frontend but also improve the overall quality and reliability of our codebase.

**Comment by yashpandey06** [comment]
@arkid15r  lets discuss over it !

**Comment by yashpandey06** [comment]
Is this issue ref to #71

**Comment by arkid15r** [comment]
Hey @yashpandey06, 
could you update this one? Are you planning to implement any tests as per your proposal and our Slack discussion?

Thank you!

**Comment by yashpandey06** [comment]
> Hey @yashpandey06, 
> could you update this one? Are you planning to implement any tests as per your proposal and our Slack discussion?
> 
> Thank you!

@arkid15r yeah , currently working on the same , can you please help tell that if we have merged mr for any testing library integration ? .

**Comment by arkid15r** [comment]
> @arkid15r yeah , currently working on the same , can you please help tell that if we have merged PR for any testing library integration ? .

https://github.com/OWASP/Nest/pull/101 has just been merged. It creates an initial setup for jest. Please feel free to improve/extend it if needed.

For the backend we already have the testing framerowk set up with some tests in `backend/tests` directory.

**Comment by yashpandey06** [comment]
> > @arkid15r yeah , currently working on the same , can you please help tell that if we have merged PR for any testing library integration ? .
> 
> https://github.com/OWASP/Nest/pull/101 has just been merged. It creates an initial setup for jest. Please feel free to improve/extend it if needed.
> 
> For the backend we already have the testing framerowk set up with some tests in `backend/tests` directory.
> 
> 

Cool that's green flag now for me ! 
Thanks 🙏
